#!/usr/bin/env bash





# Variables


rootfolder=$HOME"/.ani-cli-batch"
PATH=$rootfolder"/falsebin":$PATH

anime_count=-1
declare -a anime_name
declare -A anime_position
declare -A episode_range
declare -A anime_quality
declare -A download_location
declare -A ani_cli_arguments

exit=0


# Parse passed arguments and set global user choice variables


# These are variables that are passed to the script that it will use if the user doesn't specify a particular attribute or answers no on a choice question.
# This let's the user skip answering with the same choice for different anime and just pass a few defaults as arguments.
# Example: The user can launch ani-cli-batch with --quality 720p and every time the user answers No to "Do you want to specify a download quality?" the script will default to 720p

#default_anime_location=$1
#default_anime_quality=$2



# Functions

# Search for the anime and print the search results
searchanime() {
	echo "Enter your search query"
	read searchquery
	ani-cli $searchquery --rofi #run ani-cli's search function and save the result in ani-cli-batch's config folder using the fake rofi binary in falsebin
	clear; cat $rootfolder"/searchresults"
	echo ""
	#return "$searchquery"
}

# Save the user's query to anime_name at anime_count
savequery() {
anime_name[$anime_count]="$searchquery"
}

# Ask for and save the current anime's serial number to anime_position at anime_count
saveserial(){
	echo "What's your anime's serial number?"
	read serialnumber
	anime_position[$anime_count]=$serialnumber
}

# Set's the download range for anime corresponding to anime_count to the provided range (format:startep-endep), or to all episodes if no range is provided.
# Uses the currently saved search results. Only call after searchanime and saveserial
setrange() {
	episoderange=$1
	if [ -z $episoderange ]; then
		# Download all
		# Read the line containing the correct search result and store everything before the episode count to remove it later
		pretext=$(sed -n '${anime_position["$anime_count"]}p' $rootfolder/searchresults | sed s/\([0-9]*\ episodes\)//)
		# Remove everthing before the episode count to get the episode count
		episodecount=$(sed -n '${anime_position["$anime_count"]}p' $rootfolder/searchresults | sed s/"$pretext"// | sed s/\(// | sed s/\ episodes\)//)
		episode_range[$anime_count]="-r 1-$episodecount"
		echo "Downloading all episodes (1-$episodecount)"
		echo ""
	else
		# download specified
		episode_range[$anime_count]="-r $episoderange"
	fi
}



# Main


# Print the main menu
while [ $exit -eq 0 ]; do
	clear
	echo "This is a wrapper for ani-cli that makes it easier to batch download multiple anime"
	echo "What do you want to do?"
	echo "1.Add anime to the download queue"
	echo "2.Manage queue / Edit added entries"
	echo "3.Construct and print a download command for ani-cli"
	echo "4.Download queued anime"
	echo "5. Cancel all operations and quit"
	echo "6. Check for updates"
	echo ""

	read instruction -n 1
	echo ""

	case $instruction in
 		1|add)
			clear
			echo "1. Quick add (Quickly add multiple anime to the download queue with the same preferences (quality, download location, etc..)"
			echo "2. Customise and add (Select different settings for each anime)"
			echo ""

			read -n 1 addtype
			echo ""

			case $addtype in
				1|batch)
					# Ask for and save the download quality
					echo "Choose a download quality or leave empty to default to the highest"
					echo "Available choices: 240p 360p 480p 720p 1080p"
					read batchquality

					if [[ -z $batchquality ]]; then
						batchquality="-q 1080p"
					else
						batchquality="-q $batchquality"
					fi

					# Ask for a download location
					while true; do
						echo "Do you want to specify a download location? (y/N) ('No' downloads to your downloads folder)"
						read -n 1 setdownloadloc
						echo ""
						if [[ "$setdownloadloc" == "y" || "$setdownloadloc" == "Y" ]];then
							#Ask for a download location
							echo "Where do you want to download to? (Provide the absolute location / wrt root. Eg:/home/user/desktop)"
							echo ""
							read batchlocation
							batchlocation="cd $batchlocation && "
							break
						elif [[ -z $setdownloadloc || "$setdownloadloc" == "n" || "$setdownloadloc" == "N" ]]; then
							# Download to downloads
							mkdir -p $HOME/Downloads/ani-cli-batch && batchlocation="cd $HOME/Downloads/ani-cli-batch && "
							break
						else
							echo "Unknown choice. Please choose a valid option"
							echo ""
						fi
					done

					# Ask for and set the episode range
					echo "Do you want to download all episodes for these shows? (Y/n) (Answer with n to individually specify what epiodes to download later)"
					read -n 1 downloadall
					echo ""

					if [[ "$downloadall" -eq "n" || "$downloadall" -eq "N" ]];then
						downloadall=false
					else
						downladall=true
					fi

					# Ask for common extra ani-cli arguments
					echo "List arguments you want to pass to ani-cli here. Arguments will be passed as is. Ex: --dub"
					echo "WARNING: Any commands passed here WILL BE EXECUTED. Eg: Doing --dub; rm -rf $HOME will first download your anime and then will destroy your home folder."
					echo "Only use this field to pass extra arguments to ani-cli. Do not issue commands."
					read batcharguments

					# Ask for anime names. Perform search and queue them using defined defaults
					while true; do
						# Give an id to the anime currently being searched
						((anime_count++))

						# Perform an ani-cli search, get and display results
						searchanime

						# Save the search query using the anime id (anime_count)
						savequery

						# Ask for and save the serial number of the anime from the search results
						saveserial

						# Ask for and set the episode range
						if $downloadall; then
							setrange
						else
							echo "What range of episodes do you want to download? (startep-endep) (ex:1-17)"
							read range
							echo "$range" | setrange
						fi

						# Save the download quality
						anime_quality[$anime_count]="$batchquality"

						# Save the download location
						download_location[$anime_count]="$batchlocation"

						# Save any ani-cli arguments
						ani_cli_arguments[$animecount]="$batcharguments"

						# Ask the user if they are done adding anime and break the while loop
						echo "Add more anime? (y/n)"
						read batchadd -n 1
						echo ""

						if [[ "$batchadd" == "y" || "$batchadd" == "Y" ]]; then
							clear
						else
							break
						fi
					done
					;;
				2|Customised)
					# Give an id to the anime currently being searched
					((anime_count++))

					# Perform an ani-cli search, get and display results
					searchanime

					# Save the search query using the anime id (anime_count)
					savequery

					# Ask for and save the serial number of the anime from the search results
					saveserial

					# Ask for and set the episode range
					setrange

					# Ask for and set the download quality
					echo "Do you want to select a download quality? (y/n) (Default is 1080p)"
					read selectquality -n 1
					if [ selectquality == y ]; then
						# List quality choices and read one
						echo ""
					else
						echo ""
					fi
					
					# set download location
					# ask for extra arguments
					# clear search results
					;;
			esac
			;;
	 	2|edit)
	 		echo "Anime currently in queue"
	 		echo ""
			i=0
    		while [ $i -le $anime_count]; do
    			((i++))
				echo "$anime_count ${anime_name[$anime_count]}"
				echo ""
			done
			echo "Select an anime to view and edit chosen preferences"
			;;
		3|print)
	   		for anime in "${anime_name[@]}"; do
				# To-do : Implement download location support
				echo "ani-cli -d $anime ${anime_position[$anime]} ${anime_quality[$anime]} ${episode_range[$anime]} ${ani_cli_arguments[$anime]}"
			done
			;;
		4|download)
			
			;;
		5|cancel)
			
			;;
		6|update)
			echo "Running an update check"
			cd ~ && ani-cli-batch-update
			if [ $? -eq 0 ]; then
				echo "Update successful. Please restart ani-cli-batch"
				echo "Note: If you face any errors after updating, please update a second time!"
			else
				echo "Update failed!"
			fi
			;;
		*)
			echo "Please make a valid choice!"
			echo "Valid choices include 1, 2, 3, 4, 5 and 6. Press any key to continue"
			exit=0
			read -n 1 icannotkeepcomingupwithcoolvariablenames
			;;
	esac
done
