#!/data/data/com.termux/files/usr/bin/bash
echo "This is a wrapper for ani-cli written by Junaid Shaik, that makes it easier to batch download multiple anime"

addanime=true
command="ani-cli -d"
validchoice=false

while [ $addanime == true ]
do
   echo "What do you want to download?"
   read animename

   echo "Running ani-cli's search operation"
   echo "Exit after finding the correct S.no and episode range"
   ani-cli $animename
   #searchresult=$(timeout 5s ani-cli $animename)
   #clear
   #echo $searchresult

   echo "What number on the list was your anime?"
   read selection

   command=$(echo $command $animename -S $selection)
   clear

   echo "What range of episodes do you want to download?"
   read range

   command=$(echo $command -r $range)

   echo "Do you want to specify a download quality (y/n)?"
   read qualitychoice

   if [ $qualitychoice == y ]; then
      echo "specify the quality"
      read quality
      command=$(echo $command -q $quality)
   else 
      echo
   fi

   echo "What do you want to do?"
   echo "1.Continue adding anime"
   echo "2.Execute the download command"
   echo "3.Print the download command and await further instructions"
   echo "4.Cancel operation and quit"

   until [ $validchoice == true ]
   do
      read choice
      case $choice in
         1|add)
            command=$(echo $command "; ani-cli -d" )
            addanime=true
            validchoice=true
            ;;
         2|execute)
            #$command
            #if [ $? == 0 ]; then
            #   addanime=false
            #else
            #   echo "Download failed! Printing the download command."
            #   echo $command
            #   addanime=false
            #fi
            clear
            echo "The script's downloader is experiencing issues rn."
            echo "Just copy and paste this command as a temporary alternative"
            echo $command
            #remove the next line if you uncomment the first 8 lines in this code block.
            addanime=false
            validchoice=true
            ;;
         3|print)
            clear && echo "Printing the download command."
            echo $command
            echo "respond with a ? to view all the available choices"
            validchoice=false
            ;;
         4|cancel)
            echo "Cancelling pending operations and quitting."
            addanime=false
            validchoice=true
            ;;
         *)
            echo "Please make a valid choice!"
            echo "Valid choices include 1, 2, 3, 4, add, execute, print and cancel"
            validchoice=false
            ;;
      esac
   done
   validchoice=false
done
